name: adas-swc-workflow

on:
  workflow_call:
    inputs:
      swc-name:
        required: true
        type: string

jobs:
  experiment:
    runs-on: windows-latest
    steps:
      - uses: actions/labeler@v4
        with:
          swc-name: ${{ inputs.swc-name }}
      - run: echo ${{ env.swc-name }}
      - uses: actions/checkout@v4
