name: adas-swc-workflow

on:
  workflow_call:
    inputs:
      swc-name:
        required: true
        type: string

jobs:
  experiment:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ inputs.swc-name }}
      - id: foo
        uses: Ysuika/sdv-composite-actions/clone-test-scenario@main
        with:
          repository_url: 'https://github.com/Ysuika/test-scenario.git'
          branch_name: 'main'
